### ISSUE TITLE
ErrorException: Creating default object from empty value

### ISSUE THREAD

**Issue by joejoe2016** [TimFoerster/octobercms-leaflet#2]
Hi,
on my page I have an issue when showing a map.
I get an ErrorException: Creating default object from empty value

Any suggestions on how to solve this?
Thanks

The corresponding htm file contains
```
title = "Home"
url = "/"
layout = "default"
is_hidden = 0

[map]
map = 1
showOnlyObject = 0
fieldId = "map"
height = "400px"
latitude = 0
longitude = -60
zoom = 3
==
```

```
ErrorException: Creating default object from empty value in /hp/ct/ab/ey/www/webspace/plugins/timfoerster/leaflet/components/Map.php:126
Stack trace:
#0 /hp/ct/ab/ey/www/webspace/plugins/timfoerster/leaflet/components/Map.php(126): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Creating defaul...', '/hp/ct/ab/ey/ww...', 126, Array)
#1 /hp/ct/ab/ey/www/webspace/plugins/timfoerster/leaflet/components/Map.php(117): TimFoerster\Leaflet\Components\Map->map()
#2 /hp/ct/ab/ey/www/webspace/modules/cms/classes/CmsCompoundObject.php(172): TimFoerster\Leaflet\Components\Map->onRun()
#3 /hp/ct/ab/ey/www/webspace/modules/cms/classes/Controller.php(500): Cms\Classes\CmsCompoundObject->runComponents()
#4 /hp/ct/ab/ey/www/webspace/modules/cms/classes/Controller.php(393): Cms\Classes\Controller->execPageCycle()
#5 /hp/ct/ab/ey/www/webspace/modules/cms/classes/Controller.php(224): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#6 /hp/ct/ab/ey/www/webspace/modules/cms/classes/CmsController.php(50): Cms\Classes\Controller->run('/')
#7 [internal function]: Cms\Classes\CmsController->run('/')
#8 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#9 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#10 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')
#11 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#12 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#13 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#32 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#33 /hp/ct/ab/ey/www/webspace/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#34 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#35 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#36 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /hp/ct/ab/ey/www/webspace/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(24): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /hp/ct/ab/ey/www/webspace/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#43 /hp/ct/ab/ey/www/webspace/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#44 {main}
```

**Comment by joejoe2016** [comment]
Perhaps this is related to another error that I see
Symfony\Component\Debug\Exception\FatalErrorException: Maximum execution time of 30 seconds exceeded in \vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:105

**Comment by TimFoerster** [comment]
what is your php version and ocms build number?

**Comment by TimFoerster** [comment]
it looks like the map can not be found, do you already created the map?

**Comment by joejoe2016** [comment]
Hi Tim,
thanks for your feedback.

System build is 458, PHP Version is 7.2.21

The map is working correctly in most times on my webspace, some times (I don't know how often) the error appears.
On my local XAMPP-installation until now I have never seen the error and the map always loaded correctly until now.
I changed the execution time, let's see if this solved the error.
